### PR TITLE
[UI Fix] Update Merchant Mobile & Laptop Responsiveness

### PR DESCRIPTION
**Pull request by HannahC077**
- fixed Merchant Side UI errors for desktop
- adjusted new pages/modals/components for desktop, laptop & mobile

### CODE REVIEW

**Comment by HannahC077** [comment]
- updated Merch Calendar & Modals for Mobile
- fixed Log Out Page and Login Pages for Mobile

**Review by Katteu — APPROVED** [review]
LGTM

**Comment by Katteu** [comment]
@HannahC077 please resolve Conflict

**Comment by HannahC077** [comment]
Added Merchant Dashboard Retrieve Recent Reservations

**Review by Katteu — APPROVED** [review]
LGTM

**Pull request merged**
